<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="TransporterAService"
     targetNamespace="http://transporteraws/"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://transporteraws/"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="TransporterAService">
        <plnk:role name="TransporterAService" portType="tns:TransporterAService"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://transporteraws/" location="http://soabpm-vm.site:7001/TransporterAWS-TransporterAWS-context-root/TransporterAServiceSoap12HttpPort?wsdl"/>
</wsdl:definitions>
